fix: docker-image.yml use wrong env

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -18,6 +18,13 @@ jobs:
       - name: Set image tag
         run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
 
+      - name: Validate Docker Hub username
+        run: |
+          if [ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
+            echo "Error: DOCKER_HUB_USERNAME is not set."
+            exit 1
+          fi
+
       - name: Build the Docker image
         run: |
           docker build . \
@@ -30,9 +37,9 @@ jobs:
 
       - name: Log in to Docker Hub
         env:
-          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
-          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
-        run: docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_TOKEN"
+          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
+          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
+        run: docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN"
 
       - name: Push image to Docker Hub
-        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nghien-phim:$IMAGE_TAG
+        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nghien-phim:$IMAGE_TAG
